### Problem 1
What is the average value of the first 5 rows of the third and fourth columns?

In [1]:
import numpy as np

In [2]:
np.random.seed(21) # This guarantees the code will generate the same set of random numbers whenever executed
random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

In [3]:
req_arr=random_integers[0:5,2:4]
print('Required mean is',np.mean(req_arr))

Required mean is 286058.5


### Problem 2
In this problem, we are going to calculate distances between some pairs of points :
Create a 2-D array of 10 points where the x-coordinates and the y-coordinates can take random integral values between 5 and 20.
Next, create two 1-D arrays(one for Euclidean distance and the other for Manhattan distance) for these points

In [4]:
arr=np.random.randint(5,20,(10,2))
print(arr)

[[19 12]
 [10 16]
 [ 7 12]
 [10 19]
 [ 5  9]
 [ 7  7]
 [ 5 14]
 [16  6]
 [ 5  8]
 [ 6  8]]


In [5]:
# Calculate Euclidean distances between these pairs of points (total 10*10 = 100 pairs including self pairs). This should give you a 10*10 2-D array where each value corresponds to the distance between a pair

dis=[]
for i in range(0,10):
    a=0
    b=10
    while a<b:
        a1=arr[i]
        a2=arr[a]
        a=a+1
        sum_sq = np.sum(np.square(a1 - a2))
        dis.append(np.sqrt(sum_sq))
dis_arr=np.array(dis,dtype=int)
dis_arr=np.reshape(dis_arr,(10,10))
print(dis_arr)

[[ 0  9 12 11 14 13 14  6 14 13]
 [ 9  0  5  3  8  9  5 11  9  8]
 [12  5  0  7  3  5  2 10  4  4]
 [11  3  7  0 11 12  7 14 12 11]
 [14  8  3 11  0  2  5 11  1  1]
 [13  9  5 12  2  0  7  9  2  1]
 [14  5  2  7  5  7  0 13  6  6]
 [ 6 11 10 14 11  9 13  0 11 10]
 [14  9  4 12  1  2  6 11  0  1]
 [13  8  4 11  1  1  6 10  1  0]]


In [6]:
# Calculate Manhattan distances between these pairs of points (total 10*10 = 100 pairs inlcuding self pairs).This should give you a 10*10 2-D array where each value corresponds to the distance between a pair.

mandis=[]
for i in range(0,10):
    a=0
    b=10
    while a<b:
        a1=arr[i]
        a2=arr[a]
        a=a+1
        sum_abs = np.sum(np.absolute(a1 - a2))
        mandis.append(sum_abs)
mandis_arr=np.array(mandis)
np.reshape(mandis_arr,(10,10))

array([[ 0, 13, 12, 16, 17, 17, 16,  9, 18, 17],
       [13,  0,  7,  3, 12, 12,  7, 16, 13, 12],
       [12,  7,  0, 10,  5,  5,  4, 15,  6,  5],
       [16,  3, 10,  0, 15, 15, 10, 19, 16, 15],
       [17, 12,  5, 15,  0,  4,  5, 14,  1,  2],
       [17, 12,  5, 15,  4,  0,  9, 10,  3,  2],
       [16,  7,  4, 10,  5,  9,  0, 19,  6,  7],
       [ 9, 16, 15, 19, 14, 10, 19,  0, 13, 12],
       [18, 13,  6, 16,  1,  3,  6, 13,  0,  1],
       [17, 12,  5, 15,  2,  2,  7, 12,  1,  0]])

### Problem 3
Extract all the contiguous 3x3 blocks from a random 10x10 matrix. 

In [7]:
matrix= np.random.randint(1,100,(10,10))
print(matrix)
n = 3
i = 1 + (matrix.shape[0]-3)
j = 1 + (matrix.shape[1]-3)
all_matrix = np.lib.stride_tricks.as_strided(matrix, shape=(i, j, n, n), strides=matrix.strides + matrix.strides)
print(all_matrix)

[[ 2 28 34 33 32 67 87 75 94 90]
 [82 68  2 66 80 34 50 34 12 12]
 [78 56 37 87 82 74 30  4 95 39]
 [47 93 25 66 42  2 93 81 62 26]
 [36 11 74 69 29 17 35 42  1 57]
 [31 79  2 79 66 37 62 54  1  4]
 [ 8 33 89 54 95 11 94 24 44 40]
 [95 13 36 99 83 91 32 49 80 90]
 [19 15  4 27 45 13 66 70 55 75]
 [50  4 23  6 12 20 99 40 12  1]]
[[[[ 2 28 34]
   [82 68  2]
   [78 56 37]]

  [[28 34 33]
   [68  2 66]
   [56 37 87]]

  [[34 33 32]
   [ 2 66 80]
   [37 87 82]]

  [[33 32 67]
   [66 80 34]
   [87 82 74]]

  [[32 67 87]
   [80 34 50]
   [82 74 30]]

  [[67 87 75]
   [34 50 34]
   [74 30  4]]

  [[87 75 94]
   [50 34 12]
   [30  4 95]]

  [[75 94 90]
   [34 12 12]
   [ 4 95 39]]]


 [[[82 68  2]
   [78 56 37]
   [47 93 25]]

  [[68  2 66]
   [56 37 87]
   [93 25 66]]

  [[ 2 66 80]
   [37 87 82]
   [25 66 42]]

  [[66 80 34]
   [87 82 74]
   [66 42  2]]

  [[80 34 50]
   [82 74 30]
   [42  2 93]]

  [[34 50 34]
   [74 30  4]
   [ 2 93 81]]

  [[50 34 12]
   [30  4 95]
   [93 81 62]]

  [[34 

### Problem 4
Write a function which finds the nearest value from a given value in an array of random N elements. Suppose you created an 1-D array with 15 elements taking values between 10 and 500. Your function would take any input from these values and return the nearest value. 

In [8]:
array = np.random.randint(10,500,size=(15))
print(array)
def nearval():
    value=int(input("Give number out of 10 to 500")) 
    dist=[]
    dist.append(np.abs(array-value))
    print("The respective distances between the value and array points are \n",dist)
    dist=np.array(dist)
    n=np.argmin(dist)
    return(array[n])
nearval()

[260 207 110 309 203 228 351 218 279  89 308 417  12 473 130]
Give number out of 10 to 500120
The respective distances between the value and array points are 
 [array([140,  87,  10, 189,  83, 108, 231,  98, 159,  31, 188, 297, 108,
       353,  10])]


110