## 1.Ordinal Encoding ( Peformed on Ordinal categorical features)

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('customer.csv')

In [3]:
df.head()

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [4]:
df.shape

(50, 5)

In [5]:
df=df.iloc[:,2:]
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X=df.drop('purchased',axis=1)
Y=df['purchased']

In [8]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=10,stratify=Y)

In [9]:
print(x_train.shape)
print(x_test.shape)

(40, 2)
(10, 2)


In [10]:
df['purchased'].value_counts(normalize=True)

No     0.52
Yes    0.48
Name: purchased, dtype: float64

In [11]:
y_train.value_counts(normalize=True)

No     0.525
Yes    0.475
Name: purchased, dtype: float64

In [12]:
from sklearn.preprocessing import OrdinalEncoder


In [13]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [14]:
x_train_transformed=oe.fit_transform(x_train)
x_test_transformed=oe.transform(x_test)

In [15]:
x_train.head(3)

review education
34  Average    School
12     Poor    School
9      Good        UG

In [16]:
x_train_transformed[:3,:]

array([[1., 0.],
       [0., 0.],
       [2., 1.]])

## 2.Label Encoding (Performed on Target Column)

In [17]:
from sklearn.preprocessing import LabelEncoder


In [18]:
le=LabelEncoder()

In [19]:
y_train_encoded=le.fit_transform(y_train)
y_test_encoded=le.fit_transform(y_test)

In [20]:
y_train.values

array(['No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes',
       'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes',
       'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No'],
      dtype=object)

In [21]:
y_train_encoded

array([0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0])

## 3. One Hot Encoding (Performed on Nominal Categorical Features)

In [36]:
df2 =pd.read_csv('cars.csv')

In [37]:
df2.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [38]:
df2.brand.value_counts()

Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Kia                 4
Ambassador          4
MG                  3
Daewoo              3
Peugeot             1
Ashok               1
Opel                1
Name: brand, dtype: int64

In [39]:
print(df2['fuel'].value_counts(),'\n')
print(df2['owner'].value_counts())

Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: fuel, dtype: int64 

First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: owner, dtype: int64


In [40]:
# 1.Using Pandas
pd.get_dummies(df2,columns=['fuel','owner'])


brand  km_driven  selling_price  fuel_CNG  fuel_Diesel  fuel_LPG  \
0      Maruti     145500         450000         0            1         0   
1       Skoda     120000         370000         0            1         0   
2       Honda     140000         158000         0            0         0   
3     Hyundai     127000         225000         0            1         0   
4      Maruti     120000         130000         0            0         0   
...       ...        ...            ...       ...          ...       ...   
8123  Hyundai     110000         320000         0            0         0   
8124  Hyundai     119000         135000         0            1         0   
8125   Maruti     120000         382000         0            1         0   
8126     Tata      25000         290000         0            1         0   
8127     Tata      25000         290000         0            1         0   

      fuel_Petrol  owner_First Owner  owner_Fourth & Above Owner  \
0               0                  1                           0   
1               0                  0                           0   
2               1                  0                           0   
3               0                  1                           0   
4               1                  1                           0   
...           ...                ...                         ...   
8123            1                  1                           0   
8124            0                  0                           1   
8125            0                  1                           0   
8126            0                  1                           0   
8127            0                  1                           0   

      owner_Second Owner  owner_Test Drive Car  owner_Third Owner  
0                      0                     0                  0  
1                      1                     0                  0  
2                      0                     0                  1  
3                      0                     0                  0  
4                      0                     0                  0  
...                  ...                   ...                ...  
8123                   0                     0                  0  
8124                   0                     0                  0  
8125                   0                     0                  0  
8126                   0                     0                  0  
8127                   0                     0                  0  

[8128 rows x 12 columns]

In [41]:
# Creating (n-1) feature coulumns
pd.get_dummies(df2,columns=['fuel','owner'],drop_first=True)

brand  km_driven  selling_price  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0      Maruti     145500         450000            1         0            0   
1       Skoda     120000         370000            1         0            0   
2       Honda     140000         158000            0         0            1   
3     Hyundai     127000         225000            1         0            0   
4      Maruti     120000         130000            0         0            1   
...       ...        ...            ...          ...       ...          ...   
8123  Hyundai     110000         320000            0         0            1   
8124  Hyundai     119000         135000            1         0            0   
8125   Maruti     120000         382000            1         0            0   
8126     Tata      25000         290000            1         0            0   
8127     Tata      25000         290000            1         0            0   

      owner_Fourth & Above Owner  owner_Second Owner  owner_Test Drive Car  \
0                              0                   0                     0   
1                              0                   1                     0   
2                              0                   0                     0   
3                              0                   0                     0   
4                              0                   0                     0   
...                          ...                 ...                   ...   
8123                           0                   0                     0   
8124                           1                   0                     0   
8125                           0                   0                     0   
8126                           0                   0                     0   
8127                           0                   0                     0   

      owner_Third Owner  
0                     0  
1                     0  
2                     1  
3                     0  
4                     0  
...                 ...  
8123                  0  
8124                  0  
8125                  0  
8126                  0  
8127                  0  

[8128 rows x 10 columns]

In [42]:
# Categories with many unique values
counts=df2['brand'].value_counts()
replace = counts[counts <= 100].index
replace

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Land', 'Force', 'Isuzu', 'Kia',
       'Ambassador', 'MG', 'Daewoo', 'Peugeot', 'Ashok', 'Opel'],
      dtype='object')

In [43]:
pd.get_dummies(df2['brand'].replace(replace,'Not frequents'))

BMW  Chevrolet  Ford  Honda  Hyundai  Mahindra  Maruti  Not frequents  \
0       0          0     0      0        0         0       1              0   
1       0          0     0      0        0         0       0              0   
2       0          0     0      1        0         0       0              0   
3       0          0     0      0        1         0       0              0   
4       0          0     0      0        0         0       1              0   
...   ...        ...   ...    ...      ...       ...     ...            ...   
8123    0          0     0      0        1         0       0              0   
8124    0          0     0      0        1         0       0              0   
8125    0          0     0      0        0         0       1              0   
8126    0          0     0      0        0         0       0              0   
8127    0          0     0      0        0         0       0              0   

      Renault  Skoda  Tata  Toyota  Volkswagen  
0           0      0     0       0           0  
1           0      1     0       0           0  
2           0      0     0       0           0  
3           0      0     0       0           0  
4           0      0     0       0           0  
...       ...    ...   ...     ...         ...  
8123        0      0     0       0           0  
8124        0      0     0       0           0  
8125        0      0     0       0           0  
8126        0      0     1       0           0  
8127        0      0     1       0           0  

[8128 rows x 13 columns]

In [44]:
df2.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [46]:
X_train,X_test,y_train,y_test = train_test_split(df2.iloc[:,0:4],df2.iloc[:,-1],test_size=0.2,random_state=2)

In [47]:
X_train.head()

brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [48]:
# Using Sklearn
from sklearn.preprocessing import OneHotEncoder

In [49]:
ohe=OneHotEncoder(drop='first',sparse=False)

In [50]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])
X_test_new=ohe.transform(X_test[['fuel','owner']])

In [51]:
X_train_new.shape

(6502, 7)

In [52]:
X_train_new

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [53]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Hyundai', 35000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Jeep', 60000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Hyundai', 25000, 0.0, ..., 0.0, 0.0, 0.0],
       ...,
       ['Tata', 15000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 32500, 1.0, ..., 1.0, 0.0, 0.0],
       ['Isuzu', 121000, 1.0, ..., 0.0, 0.0, 0.0]], dtype=object)